### ISSUE TITLE
[Feature]: Remove https://visualization.suspensive.org by Sandpack playground of https://suspensive.org

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1005]
### Package Scope

etc

### Description

Remove https://visualization.suspensive.org by Sandpack playground of https://suspensive.org

**Comment by kangju2000** [comment]
https://github.com/toss/suspensive/issues/7#issuecomment-2198736852

**Comment by manudeli** [comment]
https://github.com/toss/suspensive/pull/1123#issuecomment-2247457356

Because of this reason, I close as not planned
