### ISSUE TITLE
[Feature]: chalk

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1009]
### Package Scope

@suspensive/react-query

### Description

Idea by @po4tion
https://github.com/chalk/chalk

**Comment by manudeli** [comment]
@gwansikk If you want to work with this, make @po4tion as co-author please.

**Comment by gwansikk** [comment]
@po4tion Thank you for your valuable feedback! I will try this in the next version.

**Comment by manudeli** [comment]
https://github.com/vercel/turbo/blob/52ed46b352989a12c7228cfdf45585446611bb31/packages/turbo-gen/src/cli.ts#L5

Turborepo use chalk too! chalk.bold, chalk.color could make our suspensive-react-query more readable
I look forward this feature

**Comment by manudeli** [comment]
@gwansikk 

### srq status

<img width="767" alt="image" src="https://github.com/user-attachments/assets/f73b75cc-a865-46b7-9824-78e33669aa15">

### attw

<img width="396" alt="image" src="https://github.com/user-attachments/assets/a540afd6-7dbe-47dc-92ad-ea33670c7680">

color could be added

**Comment by gwansikk** [comment]
> I think we don't have to do this because we use already color too.

I agree. I will re-open if necessary.
