### ISSUE TITLE
I have temporarily declared the API list. In the next version, I will parse the TypeScript to list and display the APIs!

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1025]
I have temporarily declared the API list. In the next version, I will parse the TypeScript to list and display the APIs!

_Originally posted by @gwansikk in https://github.com/toss/suspensive/pull/1024#discussion_r1661294759_

**Comment by manudeli** [comment]
@juno7803 This issue will be resolved by @gwansikk

**Comment by manudeli** [comment]
@gwansikk Could you do this first please

**Comment by gwansikk** [comment]
> @gwansikk Could you do this first please

I missed that. I'll get on it right away!
