### ISSUE TITLE
[Feature]: `suspensive-react-query status`'s result could be table

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1029]
### Package Scope

@suspensive/react-query

### Description

This is attw cli result. In my opinion, we can express our `suspensive-react-query status` as table like below

<img width="557" alt="image" src="https://github.com/toss/suspensive/assets/61593290/ec20e215-454b-4718-9c29-bb9c0e0a3827">

### Possible Solution

Below table is just suggestion. Could you make it better please?

||result|status|advice|
|:------:|---|:---:|---|
|**version**|@suspensive/react-query@2.4.0|🟢||
|**export**|@suspensive/react-query-4@2.4.0|🟢||
|**peerDependency**|@tanstack/react-query@5.32.0|❌|Install @tanstack/react-query@4 or excute suspensive-react-query switch 5 to match @suspensive/react-query version with @tanstack/react-query|
|**You can use**|queryOptions useSuspenseQuery useSuspenseQueries useSuspenseInfiniteQuery SuspenseQuery SuspenseQueries SuspenseInfiniteQuery QueryErrorBoundary|🟢||

**Comment by gwansikk** [comment]
Oh, that's really awesome! I'll get to it as soon as possible!
