### ISSUE TITLE
[Bug]: GitHub fetching don't work. Fetch succeeds only intermittently.

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1051]
### Bug description

https://suspensive.org/docs/contributors

<img width="1719" alt="image" src="https://github.com/toss/suspensive/assets/61593290/957f77fa-aaef-48ad-85f2-1148b0a4d052">

@saul-atomrigs Could I assign you this issue?

**Comment by saul-atomrigs** [comment]
Sure, please! 

I suspect it might be due to github API rate limit..
I'll be able to have a closer look after company work hours, but please go ahead with the assignment! 👀

**Comment by manudeli** [comment]
> Sure, please!
> 
> I suspect it might be due to github API rate limit.. I'll be able to have a closer look after company work hours, but please go ahead with the assignment! 👀

Thanks! I'll wait you for resolving this issue

**Comment by manudeli** [comment]
@saul-atomrigs I close this issue by https://github.com/toss/suspensive/pull/1056

If you other opinion, open this issue again please
