### ISSUE TITLE
[Feature]: add Suspensive React Query to TanStack Query v5 Community Resources

### ISSUE THREAD

**Issue by gwansikk** [toss/suspensive#1055]
### Package Scope

@suspensive/react-query

### Description

add Suspensive React Query to TanStack Query v5 Community Resources

**Comment by gwansikk** [comment]
@manudeli I will send PR to TanStack Query v5 Community Resources within this week!

**Comment by manudeli** [comment]
> @manudeli I will send PR to TanStack Query v5 Community Resources within this week!

Cool

**Comment by gwansikk** [comment]
@manudeli I have submitted a PR requesting to add @suspensive/react-query to the @tanstack/react-query community projects. Please review it.

- https://github.com/TanStack/query/pull/7846

**Comment by manudeli** [comment]
> @manudeli I have submitted a PR requesting to add @suspensive/react-query to the @tanstack/react-query community projects. Please review it.
> 
> * [docs: add suspensive react query to community projects TanStack/query#7846](https://github.com/TanStack/query/pull/7846)

I reviewed it now. without link, perfect for me.

**Comment by manudeli** [comment]
@gwansikk Your PR is merged now! It's really great work!🚀
