### ISSUE TITLE
[Question]: Suspense's DefinedSuspense

### ISSUE THREAD

**Issue by ssi02014** [toss/suspensive#1058]
### Package Scope

@suspensive/react

### Description

@manudeli Hi! 👋 I was looking at that code and had a question.

https://github.com/toss/suspensive/blob/main/packages/react/src/Suspense.tsx#L26

I think it's common to check `defaultProps` if there are no user-injected `props`, but the current code checks `defaultProps` and then checks `clientOnly` props that the user injects.
 
Is there a reason why it was implemented this way? 

### Possible Solution

```ts
const DefinedSuspense = clientOnly ?? defaultProps.clientOnly ? SuspenseClientOnly : ReactSuspense
```
Isn't it more common to write it like this?

I think it should be a higher priority to inject directly from `Suspense`, even if the value can be injected from `SuspensiveProvider`.

**Comment by manudeli** [comment]
Oh... god,, you catch bug...! Could I assign you to fix this bug and add test code?

**Comment by ssi02014** [comment]
@manudeli 

sure! 😄 I'll work on it and create a PR in the near future.

**Comment by ssi02014** [comment]
@manudeli 
Hmmm... I'm trying to test which component is called between `SuspenseClientOnly` and `ReactSuspense` based on the `defaultProps` and `clientOnly` props values, but it's really tricky..!!! 😭

Is there a good way to do this...?

**Comment by manudeli** [comment]
> @manudeli Hmmm... I'm trying to test which component is called between `SuspenseClientOnly` and `ReactSuspense` based on the `defaultProps` and `clientOnly` props values, but it's really tricky..!!! 😭
> 
> Is there a good way to do this...?

In my opinion, You can make util function and apply it to determine SuspenseClientOnly, ReactSuspense and it will be testable

```diff
export const Suspense = ({ clientOnly, devMode, children, fallback }: SuspenseProps) => {
  const defaultProps = useContext(SuspenseDefaultPropsContext)
- const DefinedSuspense = defaultProps.clientOnly ?? clientOnly ? SuspenseClientOnly : ReactSuspense
+ const DefinedSuspense = defineSuspense({ defaultPropsClientOnly: defaultProps.clientOnly, componentPropsClientOnly: clientOnly })

  return (
    <DefinedSuspense fallback={typeof fallback === 'undefined' ? defaultProps.fallback : fallback}>
      {children}
      <SuspenseDevMode {...devMode} />
    </DefinedSuspense>
  )
}
```

Then you can test defineSuspense function

defineSuspense should be made in `src/utils/defineSuspense.ts`
