### ISSUE TITLE
[Feature]: Separate useAwait, AwaitClient and add useAwait docs

### ISSUE THREAD

**Issue by SEOKKAMONI** [toss/suspensive#1061]
### Package Scope

@suspensive/react-await

### Description

useAwait will be useful for developers who prefer not to use Await as a component. Therefore, we are separating it and create docs to make it available to developers.

**Comment by SEOKKAMONI** [comment]
@manudeli Can you check the issue and assign it to me if you think it's useful?

**Comment by manudeli** [comment]
Sure, You mean that you want to make new page in https:/suspensive.org right?
@suspensive/react-await already is exporting useAwait.

**Comment by SEOKKAMONI** [comment]
Yes, the goal is to create an new page and guide it.

**Comment by SEOKKAMONI** [comment]
@manudeli Please close the issue
