### ISSUE TITLE
[Feature]: cacheOptions DataTag

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1088]
### Package Scope

@suspensive/cache

### Description

@SEOKKAMONI Do you know DataTag? Could you dig it and add feature first please?

https://github.com/TanStack/query/blob/main/packages/react-query/src/queryOptions.ts#L1-L50

**Comment by manudeli** [comment]
@SEOKKAMONI Can I assign you?

**Comment by SEOKKAMONI** [comment]
@manudeli Yes, please assign me!

**Comment by SEOKKAMONI** [comment]
@manudeli I thought that the DataTag could be used with cacheOptions and the return value could be inferred when only cacheKey was passed as a parameter. However, the current @suspensive/cache does not have an interface that infers the return type by passing only cacheKey. I am curious whether the current work on DataTag is in preparation for a future update, or if there is another reason for this work. If I have misunderstood anything, please let me know.

**Comment by manudeli** [comment]
> I am curious whether the current work on DataTag is in preparation for a future update, or if there is another reason for this work.

Preparation for future work. I just want to raise this issue to make you recognize this thing DataTag. This feature could be important thing to use reusable cache.

**Comment by SEOKKAMONI** [comment]
Thank you for explaining the purpose! I understand now.
