### ISSUE TITLE
[Feature]: Do we need to re-export TanStack Query v5 interfaces by @suspensive/react-query-5 too

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1096]
### Package Scope

@suspensive/react-query-5

### Description

@gwansikk In my opinion, re-exporting and marking it as deprecated jsdoc is good way to support TanStack Query v4 user to migrate to TanStack Query v5

### Possible Solution

```tsx
import { queryOptions, useSuspenseQuery, useSuspenseQueries, useSuspenseInfiniteQuery } from "@suspensive/react-query-5" // mark these as deprecated jsdoc
```

_No response_

**Comment by gwansikk** [comment]
I think re-exported functions should be clearly marked with `@deprecated` to inform users.

- If the updates are made with the goal of migration, it will be clearly indicated, making the migration process easy and fast.
- Users who originally use TanStack Query v5 can use it without confusion. (The same function names can cause confusion)

**Comment by manudeli** [comment]
> Users who originally use TanStack Query v5 can use it without confusion. (The same function names can cause confusion)

Yeah, this point is also important! Could I assign you again? @gwansikk

**Comment by gwansikk** [comment]
@manudeli Once this issue is resolved, I would like to apply for inclusion in the TanStack Query v5 community resources. I think it's the right time. What do you think?

**Comment by manudeli** [comment]
> @manudeli Once this issue is resolved, I would like to apply for inclusion in the TanStack Query v5 community resources. I think it's the right time. What do you think?

Cool! I agree
