### ISSUE TITLE
[Feature]: Differ version target

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1122]
### Package Scope

@suspensive/react-query

### Description

<img width="474" alt="image" src="https://github.com/user-attachments/assets/6602f21d-fd00-4012-9bf7-4a7c391eea62">

> Switch to a specific version of @suspensive/react-query

"Switch to exports of @suspensive/react-query"? Then in my opinion, we should change table `export` -> `exports` too.

**Comment by manudeli** [comment]
@gwansikk Don't forget this please

**Comment by gwansikk** [comment]
<img width="648" alt="image" src="https://github.com/user-attachments/assets/d16c4ae2-c3a5-44db-ad22-1587fcf97dfc">

Currently, I am working to ensure that this table is described in the same way as the official documentation.

I think the phrase "specified version" is necessary in the description of "switch <version>". Since the version is changed through the `<version>` option, I want to explain it clearly.

@manudeli

**Comment by manudeli** [comment]
> <img alt="image" width="648" src="https://private-user-images.githubusercontent.com/39869096/354815310-d16c4ae2-c3a5-44db-ad22-1587fcf97dfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTMwNzMsIm5iZiI6MTcyMjY5Mjc3MywicGF0aCI6Ii8zOTg2OTA5Ni8zNTQ4MTUzMTAtZDE2YzRhZTItYzNhNS00NGRiLWFkMjItMTU4N2ZjZjk3ZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDEzNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YWJhNTBhODQ2YmM3OTllY2RmMjg2MDFlMDgxYjQ5MmE5MjI2MmNkYTJiNTA2MzAyYzhlOTA0NzZjMzhiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KEBIA63bIOhGtGrCf2eSghyS70jH0wb3taFIiFYTnIw">
> Currently, I am working to ensure that this table is described in the same way as the official documentation.
> 
> I think the phrase "specified version" is necessary in the description of "switch ". Since the version is changed through the `<version>` option, I want to explain it clearly.
> 
> @manudeli

In my opinion, we should express which version of clearly too
1. @tanstack/react-query's version
2. @suspensive/react-query's version
3. `@suspensive/react-query-<version>`
4. @suspensive/react-query's version

**Comment by gwansikk** [comment]
> In my opinion, we should express which version of clearly too
> 
> 1. @tanstack/react-query's version
> 2. @suspensive/react-query's version
> 3. `@suspensive/react-query-<version>`
> 4. @suspensive/react-query's version

That's a great idea! The term "version" becomes much clearer. I will use this terminology moving forward.
