### ISSUE TITLE
[Feature]: check size change of visualization project depending Suspensive

### ISSUE THREAD

**Issue by kangju2000** [toss/suspensive#1126]
### Package Scope

etc

### Description

https://github.com/toss/suspensive/pull/1123#issuecomment-2247457356

Add script to check size change of real services(visualization project) depending Suspensive.

**Comment by kangju2000** [comment]
@manudeli 

Can I do this by adding to the pattern in the compressed-size-action script?

**Comment by manudeli** [comment]
Yes, I thought that way to do this👍
