### ISSUE TITLE
How about below 2 things after this Pull Request

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1149]
How about below 2 things after this Pull Request
1. Remove unsubscribe method
2. CacheStore extends Subscribable https://github.com/TanStack/query/blob/main/packages/query-core/src/subscribable.ts

_Originally posted by @manudeli in https://github.com/toss/suspensive/pull/1147#discussion_r1693266363_

**Comment by manudeli** [comment]
@SEOKKAMONI share your plan please

**Comment by SEOKKAMONI** [comment]
@manudeli I recently joined the company this week and am currently in the process of adapting. Therefore, I would like to focus solely on adapting to the company this week.

Would it be okay to resume this task starting on Saturday?

**Comment by SEOKKAMONI** [comment]
I have shared my plan in https://github.com/toss/suspensive/issues/839#issuecomment-2260228134, so please check it.

**Comment by manudeli** [comment]
Duplicated with #839
