### ISSUE TITLE
[Feature]: @suspensive/react-query-next-experimental

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1155]
### Package Scope

@suspensive/react-query, @suspensive/react-query-4, etc

### Description

Support TanStack Query v4 actively

**Comment by 2-NOW** [comment]
Can you give me more details of work on this ? I am interested in this work

**Comment by manudeli** [comment]
> Can you give me more details of work on this ? I am interested in this work

There is no @tanstack/react-query-next-experimental@4

You can see this link to check it
https://www.npmjs.com/package/@tanstack/react-query-next-experimental?activeTab=versions

But in my opinion, There is no reason to support TanStack Query v4 to make it be able to use Next.js HTML Streaming.

There is so many people using TanStack Query v4 still to support lower version browser yet.

So I want to support them to use streaming html with @suspensive/react-query-next-experimental

**Comment by manudeli** [comment]
@2-NOW See docs to know [why we support TanStack Query v4 in our doc](https://suspensive.org/docs/react-query/motivation#solution-for-the-issue-of-tanstackreact-query-v5-not-being-able-to-support-lower-version-browsers-due-to-es-private-field)

I know "this attempt to support TanStack Query v4 + Next.js App router HTML Streaming" could be failure but It will make big impact

**Comment by 2-NOW** [comment]
I have a few thoughts and i'd love to know what you think

experimental features are open to change, including the interface.
the idea is that it would be inconvenient for users to have to modify a feature they use in suspicious because of a breaking change in the original feature, tanstack query, due to a change in the experimental feature.

important thing, i think that the layer that provides intermediate compatibility should be stable.

**Comment by manudeli** [comment]
> important thing, i think that the layer that provides intermediate compatibility should be stable.

In my opinion, TanStack don't modify @tanstack/react-query@^4 so that make us to get quite good stability to support @suspensive/react-query-next-experimental as TanStack Query v4 community resources. and @tanstack/react-query-next-experimental is quite stable for me. maybe they will convert its name as @tanstack/react-query-next soon.

In open source world, In my opinion, early timing to support something could be good for our getting library users choice too. so I think this timing could be good to support @suspensive/react-query-next-experimental too

**Comment by manudeli** [comment]
And We support @tanstack/react-query@^5 too by @suspensive/react-query(internally @suspensive/react-query-4, @suspensive/react-query-5 made by @gwansikk).

@suspensive/react-query-5 re-export to help migration from "TanStack Query v4 + @suspensive/react-query" to "TanStack Query v5 + @suspensive/react-query"

### TanStack Query v4 + @suspensive/react-query

```tsx
import { useSuspenseQuery } from '@suspensive/react-query' // This re-export @suspensive/react-query-4's useSuspenseQuery
```

### TanStack Query v5 + @suspensive/react-query

```tsx
import { useSuspenseQuery } from '@suspensive/react-query' // This re-export @tanstack/react-query's useSuspenseQuery
```

Then, In my opinion, @suspensive/react-query-next-experimental could be implemented similar with @suspensive/react-query's way

### TanStack Query v4 + @suspensive/react-query-next-experimental

```tsx
import { ReactQueryStreamedHydration } from '@suspensive/react-query-next-experimental' // This re-export @suspensive/react-query-next-experimental-4's ReactQueryStreamedHydration
```

### TanStack Query v5 + @suspensive/react-query-next-experimental

```tsx
import { ReactQueryStreamedHydration } from '@suspensive/react-query-next-experimental' // This re-export @tanstack/react-query-next-experimental's ReactQueryStreamedHydration
```

**Comment by 2-NOW** [comment]
I assume you're expecting the experimental feature to become stable soon, if so,
I completely agree that supporting it would be a big impact.
I'll look into implementing that feature soon :) Thanks.

**Comment by manudeli** [comment]
@gwansikk Could you support @2-NOW later to make @suspensive/react-query-next-experimental? In my opinion, you will be best person to support it.

@kangju2000 @bigsaigon333 @SEOKKAMONI I unassigned to narrowen assignee to focus who do this. but if you guys have interest in it. then let me know to assign you guys please

**Comment by gwansikk** [comment]
> @gwansikk Could you support @2-NOW later to make @suspensive/react-query-next-experimental? In my opinion, you will be best person to support it.

@2-NOW Thank you very much for your contribution. I will assist you with features that universally support two packages version(`@suspensive/react-query-next-experimenta`l & `@tanstack/react-query-next-experimental`), such as `@suspensive/react-query`

**Comment by manudeli** [comment]
Show coauthors
