### ISSUE TITLE
[Question]: Why do we manage usePrevious together inside useIsChanged?

### ISSUE THREAD

**Issue by ssi02014** [toss/suspensive#1166]
### Package Scope

@suspensive/react

### Description

I think it's better to split them up, what do you think?

### to-be
```ts
// usePrevious.ts
import { useEffect, useRef } from 'react'

export const usePrevious = <TValue>(value: TValue): TValue => {
  const ref = useRef<TValue>(value)

  useEffect(() => {
    ref.current = value
  }, [value])

  return ref.current
}
```
```ts
// useIsChanged.ts
import { usePrevious } from './usePrevious'

export const useIsChanged = (value: unknown) => usePrevious(value) !== value
```

**Comment by manudeli** [comment]
> ### Package Scope
> @suspensive/react
> 
> ### Description
> I think it's better to split them up, what do you think?
> 
> ### Possible Solution
> ### to-be
> ```ts
> // usePrevious.ts
> import { useEffect, useRef } from 'react'
> 
> export const usePrevious = <TValue>(value: TValue): TValue => {
>   const ref = useRef<TValue>(value)
> 
>   useEffect(() => {
>     ref.current = value
>   }, [value])
> 
>   return ref.current
> }
> ```
> 
> ```ts
> // useIsChanged.ts
> import { usePrevious } from './usePrevious'
> 
> export const useIsChanged = (value: unknown) => usePrevious(value) !== value
> ```
> 
> ### etc.
> _No response_

Cool, Could I assign you to do this issue?
In my opinion, @suspensive/utils could be good place to contain it too.

But usePrevious have no use case in other package, so do this in only @suspensive/react first.

**Comment by ssi02014** [comment]
@manudeli Yes! 🤗 I will create a pull request after working on it as soon as possible.
