### ISSUE TITLE
[Feature]: new `<Use />`: Component to make Hook into component easily

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1167]
### Package Scope

@suspensive/react

### Description

`<Use />` idea by @minuukang 

```tsx
<Use hook={useSuspenseQuery} params={[...params]}>
  {(result) => ...}
</Use>

const SuspenseQuery = hookComponent(useSuspenseQuery)
```
Component to make Hook into component easily

**Comment by SEOKKAMONI** [comment]
Wow, that's such a great idea!

**Comment by bigsaigon333** [comment]
I think this is a good idea, too. 👍🏻

I suggest we provide an interface with functions that have no parameters or only one parameter.

Let’s think about the `useQuery` hook from @tanstack/react-query.

In v3 and v4, `useQuery` can have up to three parameters, but in v5, it takes only one parameter. 

Limiting the number of parameters makes it much easier to implement the `Use` Component. 😄

**Comment by manudeli** [comment]
> I think this is a good idea, too. 👍🏻
> 
> I suggest we provide an interface with functions that have no parameters or only one parameter.
> 
> Let’s think about the `useQuery` hook from @tanstack/react-query.
> 
> In v3 and v4, `useQuery` can have up to three parameters, but in v5, it takes only one parameter.
> 
> Limiting the number of parameters makes it much easier to implement the `Use` Component. 😄

Hmm, but In my opinion, this should be closed...! because This `<Use/>` can't be used with hooks have function overriding 🥲. I close this issue now. but if anyone have solution, reopen please.

<img width="2173" alt="image" src="https://github.com/user-attachments/assets/f94e7892-fc1d-4e1d-ad5d-61d15fb51266">
