### ISSUE TITLE
[Feature]: Consider thrown thing should be Error

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1186]
### Package Scope

@suspensive/cache

### Description

https://x.com/TkDodo/status/1819335882970718222?t=pnf_EMCov3H06BThGZg7BQ&s=19

I just want to share this to make you @SEOKKAMONI consider this idea

There is no todo to fix ours. But consider this idea to improve our library please if you agree

**Comment by SEOKKAMONI** [comment]
I think it's a great idea. In React Query v4, the experience of errors being returned as unknown types was not favorable for TypeScript users, as it required additional type narrowing. With this idea, consistent type returns and explicit error returns through the Error type will provide a much better experience than before. Let's gradually improve together! For now, it seems that prioritizing the functionality of returning properties for errors is important.
