### ISSUE TITLE
[Feature]: Update pnpm v8 to v9

### ISSUE THREAD

**Issue by sungh0lim** [toss/suspensive#1199]
### Package Scope

etc

### Description

Have you looked at the release of [pnpm v9.0.0](https://github.com/pnpm/pnpm/releases/tag/v9.0.0) by any chance?

These changes will be good for suspensive.
- Corepack compatiblity
- Lockfile changes

**Comment by manudeli** [comment]
Thanks for your suggestion. Already I knew it. but It had bug for our release process related with pnpm 9. and Suspensive use peerDependency as very seriously

<img width="417" alt="image" src="https://github.com/user-attachments/assets/fcf9db05-b3b2-486d-a3c3-2d28fff5b3e6">

When this bug fixed, I'll try it 🙇

**Comment by manudeli** [comment]
Your contribution is also good for us if you okay! 👍

**Comment by sungh0lim** [comment]
Could you explain bug with peerDependency?

**Comment by manudeli** [comment]
> Could you explain bug with peerDependency?

When using PNPM 9, `workspace:^2.9.0` changes to `^2.9.02.9.0` at publish time. Our expected outcome was `^2.9.0`, and this worked correctly in PNPM 8.

**Comment by sungh0lim** [comment]
I'll try it this weekend :)

**Comment by gwansikk** [comment]
- https://github.com/pnpm/pnpm/issues/8355

I have found a similar issue.

**Comment by gwansikk** [comment]
> When using PNPM 9, workspace:^2.9.0 changes to ^2.9.02.9.0 at publish time. Our expected outcome was ^2.9.0, and this worked correctly in PNPM 8. 🥲

@manudeli @sungh0lim I'm working on trying to resolve that issue.

- https://github.com/pnpm/pnpm/pull/8383

**Comment by manudeli** [comment]
@gwansikk's pull request is merged. let's do this issue. I'll assign @sungh0lim on this issue

**Comment by sungh0lim** [comment]
@gwansikk It's so cool!!! When https://github.com/pnpm/pnpm/pull/8383 deployed, I update pnpm version of suspensive.

**Comment by gwansikk** [comment]
> @gwansikk It's so cool!!! When [pnpm/pnpm#8383](https://github.com/pnpm/pnpm/pull/8383) deployed, I update pnpm version of suspensive.

It has been released with pnpm@9.7.1!​

- https://github.com/pnpm/pnpm/releases/tag/v9.7.1

**Comment by manudeli** [comment]
coauthors test
