### ISSUE TITLE
> Oh..! Could you do it after merging this Pull Request? in my opinion, React Query version could be matter for your comment's point!

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1230]
> Oh..! Could you do it after merging this Pull Request? in my opinion, React Query version could be matter for your comment's point!

Sure, I'll try it after this PR is merged

_Originally posted by @gwansikk in https://github.com/toss/suspensive/issues/1229#issuecomment-2303919044_

**Comment by gwansikk** [comment]
I will resolve this issue over the weekend..!
