### ISSUE TITLE
[Feature]: add jsdoc for suspensive/jotai api

### ISSUE THREAD

**Issue by gwansikk** [toss/suspensive#1235]
### Package Scope

@suspensive/jotai

### Description

add jsdoc to suspensive/jotai api

example:
```ts

/**
 * This hook is wrapping useQuery of `@tanstack/react-query` v4 with default suspense option.
 * @see {@link https://suspensive.org/docs/react-query/useSuspenseQuery}
 */
export function useSuspenseQuery<>()
```

**Comment by manudeli** [comment]
> ### Package Scope
> @suspensive/jotai
> 
> ### Description
> add jsdoc to suspensive/jotai api
> 
> example:
> 
> ```ts
> /**
>  * This hook is wrapping useQuery of `@tanstack/react-query` v4 with default suspense option.
>  * @see {@link https://suspensive.org/docs/react-query/useSuspenseQuery}
>  */
> export function useSuspenseQuery<>()
> ```
> 
> ### Possible Solution
> _No response_
> 
> ### etc.
> _No response_

Cool!
