### ISSUE TITLE
[Feature]: typescript-eslint 8

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1238]
### Package Scope

etc

### Description

@vr-varad Could you do this please?

**Comment by vr-varad** [comment]
@manudeli Yeah sure !!!!

**Comment by manudeli** [comment]
> @manudeli Yeah sure !!!!

Thanks! I assigned you

**Comment by manudeli** [comment]
@vr-varad I made eslint 9 already! and I co-authored you too. I was quite simple than I expected. so could you version up for typescript-eslint please instead?

**Comment by vr-varad** [comment]
Yeah sure!!
