### ISSUE TITLE
[Feature]: Implement all interfaces of @tanstack/react-query@5 if we can

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1251]
### Package Scope

@suspensive/react-query

### Description

Implement all interfaces of @tanstack/react-query@5 if we can

**Comment by gwansikk** [comment]
- [ ] HydrationBoundary
- [ ] useMutationState
- [x] infiniteQueryOptions
- [x] queryOptions
- [x] useInfiniteQuery
- [x] useMutation
- [x] usePrefetchInfiniteQuery
- [x] usePrefetchQuery
- [x] useSuspenseInfiniteQuery
- [x] useSuspenseQueries
- [x] useSuspenseQuery

**Comment by gwansikk** [comment]
The necessary APIs have been implemented. I will open an issue when needed.
