### ISSUE TITLE
[Docs] docs for usePrefetchQuery, usePrefetchInfiniteQuery

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1253]
[Docs] docs for usePrefetchQuery, usePrefetchInfiniteQuery
We need to make docs after this pr being merged

**Comment by manudeli** [comment]
@gwansikk Can I assign you?

**Comment by gwansikk** [comment]
> @gwansikk Can I assign you? There is doc for https://tanstack.com/query/latest/docs/framework/react/reference/usePrefetchQuery already too

Of course, I'll try to do it as soon as possible.

**Comment by manudeli** [comment]
Share your proximate plan or due date please

**Comment by gwansikk** [comment]
> Share your proximate plan or due date please If you're too busy to resolve this issue, you can give me this issue back

- I am currently unable to work on Suspensive due to personal matters. I apologize for this. This is expected to be resolved by next week, and I promise to complete the tasks assigned to me within two weeks.
- If the work on this issue is urgent, I would appreciate it if you could take care of it.

**Comment by manudeli** [comment]
> > Share your proximate plan or due date please If you're too busy to resolve this issue, you can give me this issue back
> 
> * I am currently unable to work on Suspensive due to personal matters. I apologize for this. This is expected to be resolved by next week, and I promise to complete the tasks assigned to me within two weeks.
> * If the work on this issue is urgent, I would appreciate it if you could take care of it.

It's not urgent! After resolve your personal matters, do this please

**Comment by gwansikk** [comment]
Thank you! 😍 @manudeli
