### ISSUE TITLE
[Feature]: test coverage 100% for @suspensive/react-query

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1292]
### Package Scope

@suspensive/react-query

### Description

![image](https://github.com/user-attachments/assets/98e3d7d2-d150-47f8-acf3-4c71d1c15f28)

**Comment by saul-atomrigs** [comment]
hi, may I contribute to this issue? @gwansikk @manudeli

**Comment by gwansikk** [comment]
> hi, may I contribute to this issue? @gwansikk @manudeli 

Of course!

**Comment by manudeli** [comment]
Of course!

**Comment by gwansikk** [comment]
@saul-atomrigs The project structure of the react-query package may change. Could you wait a bit before starting work?

- https://github.com/toss/suspensive/pull/1370

**Comment by saul-atomrigs** [comment]
@gwansikk 
Thank you for reminder, I'll wait 😄

**Comment by gwansikk** [comment]
@saul-atomrigs You can proceed with this task now!

**Comment by saul-atomrigs** [comment]
Thanks! @gwansikk
