### ISSUE TITLE
[Feature]: eslint markdown, json

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1295]
### Package Scope

etc

### Description

Lint!

**Comment by kangju2000** [comment]
I believe applying [@eslint/markdown](https://github.com/eslint/markdown) could help us write code blocks more consistently. Would it be okay if I take a look into this?

**Comment by manudeli** [comment]
> I believe applying [@eslint/markdown](https://github.com/eslint/markdown) could help us write code blocks more consistently. Would it be okay if I take a look into this?

Sure!

**Comment by manudeli** [comment]
json is not must have so I close this issue!❤️ @kangju2000 Thanks!
