### ISSUE TITLE
[Feature]: usePrefetchInfiniteQuery, PrefetchInfiniteQuery type test is required

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#1298]
### Package Scope

@suspensive/react-query

### Description

type test is required to prove that we can use usePrefetchInfiniteQuery & PrefetchInfiniteQuery with infiniteQueryOptions & literally too

**Comment by gwansikk** [comment]
Could you please provide more details about this issue? Currently, there is a test case that involves usePrefetchInfiniteQuery and PrefetchInfiniteQuery being used together with infiniteQueryOptions
