### ISSUE TITLE
[Feature]: Migrate framer-motion to motion Package in `docs/suspensive.org`

### ISSUE THREAD

**Issue by yumin-jung** [toss/suspensive#1392]
### Package Scope

etc

### Description

The framer-motion package has officially transitioned to the new name [motion](https://motion.dev/).

To keep our project up-to-date and aligned with best practices, we should migrate all dependencies and imports from framer-motion to motion.

### Possible Solution

1. Update package.json:

```diff
{
  "dependencies": {
-    "framer-motion": "^11.13.1"
+    "motion": "latest"
  }
}
```

2. Update Codebase Imports:

```diff
- import { motion } from "framer-motion";
+ import { motion } from 'motion/react';
```

**Comment by gwansikk** [comment]
Thank you for your feedback. We are aware of the issue and are working on it. We will do our best to update the documentation as soon as possible.

related:

- https://github.com/toss/suspensive/pull/1389

**Comment by manudeli** [comment]
Thanks @yumin-jung, we reflected your suggestion. So I close this issue
