### ISSUE TITLE
[Feature]: migrate to nx

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#396]
### Package Scope

etc

### Description

turbo to nx

**Comment by minsoo-web** [comment]
Why would you move from turbo to nx?

**Comment by manudeli** [comment]
Because nx support [configuring project in each package's package.json](https://nx.dev/reference/project-configuration#dependent-tasks-output). It make us feel easy to manage each project's dependencies to other projects
turbo don't support it yet.

Actually, this issue is really minor yet. but I just made this issue to consider it to manage packages easily in long term perspective

**Comment by minsoo-web** [comment]
Thank you for your kind reply!

**Comment by manudeli** [comment]
https://github.com/vercel/turbo/issues/986

There is no watch mode in turborepo but nx support it. 

https://nx.dev/nx-api/nx/documents/watch

https://github.com/TanStack/query/blob/main/package.json#L26C8-L26C8

**Comment by manudeli** [comment]
https://github.com/suspensive/react/issues/551 It's related with this
