### ISSUE TITLE
[Feature]: DevMode draggable

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#522]
### Package Scope

@suspensive/react

### Description

Draggable DevMode

**Comment by manudeli** [comment]
@minsoo-web @okinawaa I think it's last feature to make `<DevMode/>` as stable.
I thought that DevMode should be rendered on react portal to be draggable.

I guess this have two requirement.
1. make DevMode draggable
2. remember previous position of DevMode in localstorage

**Comment by minsoo-web** [comment]
I'm wondering what value there might be in making it draggable.

**Comment by manudeli** [comment]
I thought devMode's position need to be like [iPhone's AssistiveTouch](https://support.apple.com/en-us/111794)

We have position already. but we need to code other postion to avoid blocking uis if there is blocked uis by DevMode. I thought it' not good for DX. so I just want to make DevMode's position should be changeable and draggable and It will make library users won't feel annoying DevMode's position problem.

<img width="355" alt="image" src="https://github.com/suspensive/react/assets/61593290/e7666f31-341e-48d1-908a-3856b78c7d9f">

I'm curious about your opinion for this feature. @minsoo-web

**Comment by manudeli** [comment]
I added this as v2 minor feature

**Comment by minsoo-web** [comment]
Oh, I think I've been in the situation you're talking about. I agree that it's not a good DX when the dev tool covers the ui. 

I think it's a good idea to make it draggable! 
However, I'm a little doubtful that it's possible to develop **lightweight**. 
It seems like you need to use `Portal` and make it lightweight **without any additional libraries**, so why not separate `DevMode` into a separate library? like `@suspensive/devtools`

**Comment by manudeli** [comment]
@minsoo-web, you are right. I thought it like you too.
[If we have to use portal, we must use react-dom](https://react.dev/reference/react-dom/createPortal). 
so I think @suspensive/react-dev-mode should be seperated with @suspensive/react If we need to implement this

To do this, I thought "overriding type interface" with d.ts file to support devMode prop externally like [typing extends theme of emotion ThemeProvider](https://emotion.sh/docs/typescript#define-a-theme)

like below

```tsx
// Suspense.tsx
interface SuspenseProps extends ReactSuspenseProps, DevModePropOverride["Suspense"] {
  ...
}
```

```ts
// suspensive.d.ts on library user's code
import { SuspensiveDevModeProp } from '@suspensive/react-dev-mode'

declare module '@suspensive/react' {
  export interface DevModePropOverride extends SuspensiveDevModeProp {}
}
```
