### ISSUE TITLE
[Feature]: separating server / client component 

### ISSUE THREAD

**Issue by minsoo-web** [toss/suspensive#669]
### Package Scope

@suspensive/react, @suspensive/react-query, @suspensive/react-await, @suspensive/react-image

### Description

I don't want see this build logs for my SPA app. 

How about separating build versions for server components like next, or adding `'use client'` directly where the user uses it?

![image](https://github.com/suspensive/react/assets/57122180/74f8871c-a17a-4629-b9fa-df993743b664)

### Possible Solution

The first thing to do is to delete the `banner` part of `tsup.config`

You can also call use client directly, or change the import path to

```
import { Suspicious } from "@suspensive/react/client/index.js"
````

instead?

### etc.

I'm using 

```
"vite": "^4.2.0",
"@suspensive/react": "^1.25.3",
"@suspensive/react-image": "^0.0.10",
```

**Comment by manudeli** [comment]
@minsoo-web I close this issue as not plan. if you matter, reopen this issue please
