### ISSUE TITLE
[Feature]: Support codesandbox to provide interactive examples

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#7]
### **Package Scope**
docs

- [x] Add to an existing package
- [ ] New package

Package name:

**Comment by manudeli** [comment]
@minsoo-web How about making Pull Request for adding codesandbox embed in documentation
Let's make our documentation like Panda CSS. Can I assign you with me?

**Comment by minsoo-web** [comment]
Of course. It is my pleasure. I will do my best 🚀🚀🚀

**Comment by minsoo-web** [comment]
<img width="925" alt="image" src="https://github.com/suspensive/react/assets/57122180/81ff4b50-f5f1-455c-a5fa-b731bbb61709">

How about like this case ? 
https://polaris.shopify.com/components/typography/text

**Comment by manudeli** [comment]
ref https://github.com/codesandbox/sandpack

**Comment by manudeli** [comment]
@minsoo-web Could I assign you for v2 docs soon?

@sonsurim We need someone have no experience for this library to see how difficulty to onboard with this. Could you be the one to see it objectively?

**Comment by minsoo-web** [comment]
> @minsoo-web Could I assign you for v2 docs soon?

Of course, I'll work on it

**Comment by sonsurim** [comment]
> @sonsurim We need someone have no experience for this library to see how difficulty to onboard with this. Could you be the one to see it objectively?

@manudeli 
Sure, that's great, I'll see it out and leave a comment!

**Comment by sonsurim** [comment]
@manudeli I was just wondering, Can I see it when it's done?

**Comment by manudeli** [comment]
> @manudeli I was just wondering, Could I see it when it's done?

I guess it's done, v2 will be release until at least in March, After then We need to do this work(codesandbox for interactive examples) in v2

**Comment by manudeli** [comment]
### reference
https://github.com/TanStack/query/blob/main/.codesandbox/ci.json

<img width="1169" alt="image" src="https://github.com/suspensive/react/assets/61593290/41eb5196-3d20-40e8-922e-ace86493b102">

**Comment by minsoo-web** [comment]
@manudeli 

I'd like to ask for your opinion, the docs of [@chara-ui/react](https://chakra-ui.com/docs/components/accordion/usage#usage), which I'm using as a reference, are provided as a library called [react-live](https://formidable.com/open-source/react-live/). I'm impressed that you can add scope, so that you can modify only the code blocks you need without separate function declarations and import syntax.

However, I think the import syntax is necessary information for the user, and the function declaration and use-case should also show the entire code. I'd love to hear your thoughts on whether using `react-live` or `sandpack` is the right way to go!

**Comment by manudeli** [comment]
@minsoo-web This issue is important. share plan please if you can

**Comment by manudeli** [comment]
@kangju2000 @minsoo-web Make and share plan to implement this feature on https://suspensive.org/ please

**Comment by kangju2000** [comment]
The differences in markdown rules on react.dev are as follows:

- Import Sandpack component at the top
- Pass dependencies as component props (on react.dev, these are written in code blocks)

**Comment by manudeli** [comment]
> @manudeli @minsoo-web
> 
> While searching for references, I came across a plugin called [remark-sandpack](https://github.com/thecuvii/remark-sandpack)
> 
> On react.dev, they compile MDX directly, but since Suspensive uses Nextra, we can attach the remark plugin.
> 
> If you use the plugin, here's how to do it:
> 
> ### Register remark plugin
> next.config.js
> 
> ```diff
> // eslint-disable-next-line @typescript-eslint/no-var-requires, import/order
> const { remarkSandpack } = require('remark-sandpack')
> 
> // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-unsafe-assignment, import/order
> const withNextra = require('nextra')({
>   theme: 'nextra-theme-docs',
>   themeConfig: './theme.config.tsx',
>   defaultShowCopyCode: true,
> +  mdxOptions: {
> +    remarkPlugins: [remarkSandpack],
> +  },
> })
> 
> /** @type {import('next').NextConfig} */
> module.exports = withNextra({
>   i18n: {
>     locales: ['en', 'ko'],
>     defaultLocale: 'en',
>   },
> })
> ```
> 
> ### Usage
> ```mdx
> import { Sandpack } from '@/components'
> 
> <Sandpack  
>   customSetup={{
>     dependencies: {
>       '@suspensive/react': 'latest',
>       '@suspensive/react-query': 'latest',
>       '@tanstack/react-query': '^4.0.0',
>     },
>   }}
> >
> 
> ```js /App.tsx
> import Example from './Example'
> import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
> const queryClient = new QueryClient()
> 
> export default function App() {
>   return (
>     <QueryClientProvider client={queryClient}>
>       <Example />
>     </QueryClientProvider>
>   )
> }
> ```
> 
> ```js /Example.tsx active
> import { wrap } from '@suspensive/react'
> import { useSuspenseQuery } from '@suspensive/react-query'
> import { api } from './api'
> 
> export default wrap
>   .ErrorBoundaryGroup({ blockOutside: false })
>   .ErrorBoundary({ fallback: ({ error }) => <>{error.message}</> })
>   .Suspense({ fallback: <>loading...</>, clientOnly: true })
>   .on(() => {
>     const query = useSuspenseQuery({
>       queryKey: ['key'],
>       queryFn: () => api.text(),
>     })
>     return <>{query.data.text}</>
>   })
> ```
> 
> ```js /api.ts
> export const api = {
>   text: async () => {
>     await new Promise((resolve) => setTimeout(resolve, 1000))
>     return { text: 'Hello, Suspensive!' }
>   },
> }
> ```
> 
> </Sandpack>
> ```
> 
> ### Result
>  2024-06-24.1.32.43.mov 
> How about using this instead of implementing it ourselves?

Wow.........!!!!!!!!! So much coooo! Could you make Pull Request too?

**Comment by manudeli** [comment]
@kangju2000 
Could you make playgrounds of Suspensive 1 page by 1 page or 1 feature by 1 feaure please?

**Comment by kangju2000** [comment]
- [ ] @suspensive/react
  - [ ] `Migrating to v2`
  - [ ] `<Suspense />`
  - [x] `<ErrorBoundary />`
  - [x] `<ErrorBoundaryGroup />`
  - [ ] `<Delay />`
  - [ ] `<SuspensiveProvider />`
  - [ ] `<DevMode />`
  - [ ] `wrap`
- [ ] @suspensive/react-query
  - [ ] `Migrating to v2`
  - [x] `useSuspenseQuery`
  - [x] `useSuspenseQueries`
  - [x] `useSuspenseInfiniteQuery`
  - [x] `queryOptions`
  - [ ] `<SuspenseQuery />`
  - [ ] `<SuspenseQueries />`
  - [ ] `<SuspenseInfiniteQuery />`
  - [ ] `<QueryErrorBoundary />`
- [ ] @suspensive/react-await
  - [ ] `<Await />`
- [ ] @suspensive/react-image
  - [ ] `<Image />`
