### ISSUE TITLE
[Feature]: add doc for shouldCatch prop

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#952]
### Package Scope

@suspensive/react

### Description

add doc for shouldCatch prop

**Comment by manudeli** [comment]
@jgjgill Could you make this doc please? I think you understood this shouldCatch prop

**Comment by jgjgill** [comment]
Oh, there was a related issue.
If I can help, I'd be happy to take it from there.
Thanks. 🙇‍♂️
