### ISSUE TITLE
[Feature]: update Suspensive React Query section in TanStack Query v4 official doc

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#956]
### Package Scope

@suspensive/react-query

### Description

queryOptions

**Comment by manudeli** [comment]
@gwansikk After we get cli, I'll try register our library as COMMUNITY RESOURCES on TanStack Query v5 official doc, not only v4

**Comment by manudeli** [comment]
@gwansikk I want to assign you to update [Community Resources section in official doc of @tanstack/react-query v5](https://tanstack.com/query/latest/docs/framework/react/community/community-projects)

I believe @suspensive/react-query support for TanStack Query v5 wouldn't have been possible without you. Therefore, I would appreciate it if you could take the initiative to add relevant information to their official documentation.

**Comment by manudeli** [comment]
- [Community Resource of TanStack Query v4](https://tanstack.com/query/v4/docs/framework/react/community/suspensive-react-query)
- [Pull Requests related with "suspensive"](https://github.com/TanStack/query/pulls?q=suspensive)

**Comment by gwansikk** [comment]
> @gwansikk I want to assign you to update [Community Resources section in official doc of @tanstack/react-query v5](https://tanstack.com/query/latest/docs/framework/react/community/community-projects)
> 
> I believe @suspensive/react-query support for TanStack Query v5 wouldn't have been possible without you, GwanSik Kim. Therefore, I would appreciate it if you could take the initiative to add relevant information to their official documentation.

Great, I'll give it a try. Can I complete the CLI Docs (https://github.com/toss/suspensive/issues/983) part first? Since I think the CLI is a tool to use @tanstack/react-query v5, updating the official documentation and then attempting it seems more convincing.

**Comment by manudeli** [comment]
> > @gwansikk I want to assign you to update [Community Resources section in official doc of @tanstack/react-query v5](https://tanstack.com/query/latest/docs/framework/react/community/community-projects)
> > I believe @suspensive/react-query support for TanStack Query v5 wouldn't have been possible without you, GwanSik Kim. Therefore, I would appreciate it if you could take the initiative to add relevant information to their official documentation.
> 
> Great, I'll give it a try. Can I complete the CLI Docs (#983) part first? Since I think the CLI is a tool to use @tanstack/react-query v5, updating the official documentation and then attempting it seems more convincing.
> 
> I promise to complete it within 2-3 days: #983, #956.

Sure I want to follow your guide! Let's try it!

**Comment by gwansikk** [comment]
I have submitted a PR to TanStack Query v4!

- https://github.com/TanStack/query/pull/7678

**Comment by gwansikk** [comment]
@manudeli It has been merged into the official documentation! I will track adding it to the TanStack Query v5 official docs in a new issue.
