### ISSUE TITLE
[Feature]: update doc for universal @suspensive/react-query

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#960]
### Package Scope

@suspensive/react-query

### Description

Thanks to @gwansikk !

**Comment by manudeli** [comment]
@gwansikk could you please update this feature in https://suspensive.org yourself?

**Comment by gwansikk** [comment]
> @gwansikk could you please update this feature in https://suspensive.org yourself?

Of course! I’m currently working on that.

**Comment by manudeli** [comment]
@gwansikk not at once is better for me! Gradually please!

**Comment by manudeli** [comment]
One page by one page or one section by one section also okay
