### ISSUE TITLE
@suspensive/react-query's JavaScript script to TypeScript

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#961]
In my opinion, it seems possible to change to TypeScript. Let's try this in the next version.

_Originally posted by @manudeli in https://github.com/toss/suspensive/pull/953#discussion_r1648820232_

**Comment by jungwoo3490** [comment]
Can I resolve this issue?

**Comment by gwansikk** [comment]
@jungwoo3490  Yes, welcome!

**Comment by manudeli** [comment]
> @jungwoo3490 Yes, welcome!

@gwansikk Could you assign to him yourself

**Comment by manudeli** [comment]
@jungwoo3490 In my opinion, duplicated with https://github.com/toss/suspensive/issues/962. I think assigning @gwansikk to this issue is better because @gwansikk created this features. but I'll assign @jungwoo3490 to https://github.com/toss/suspensive/issues/962 for reviewer or suggestion giver! Care it please!
