### ISSUE TITLE
[Feature]: Add tool to diff Library size between main and change in Pull Request

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#967]
### Package Scope

etc

### Description

Add tool to diff Library size between main and change in Pull Request

**Comment by kangju2000** [comment]
I've gathered a list of tools for comparing bundle sizes.

If you know of any better tools, please let me know.

## 1. [size-limit](https://github.com/ai/size-limit) / [size-limit-action](https://github.com/andresz1/size-limit-action)
![image](https://github.com/toss/suspensive/assets/23312485/3acdd388-94bb-4200-9af0-e478e0e1bb64)

## 2. [compressed-size-action](https://github.com/preactjs/compressed-size-action) 

|||
|---|---|
|<img src="https://github.com/toss/suspensive/assets/23312485/e424700c-0496-460e-a34a-6b7d4f42fc97" />|<img src="https://github.com/toss/suspensive/assets/23312485/0f28938a-a15d-4dcc-9015-d0c557e76c8d" />

## 3. [bundlesize](https://github.com/siddharthkp/bundlesize) 
![image](https://github.com/toss/suspensive/assets/23312485/7d9b7dce-c4a8-415f-b96d-ad5bec8c759c)

## 4. [bundlewatch](https://github.com/bundlewatch/bundlewatch) 
![image](https://github.com/toss/suspensive/assets/23312485/27036599-2cb3-4de7-ba3b-663fa9315d58)

**Comment by manudeli** [comment]
@kangju2000 may have vacation. Could I assign you @bigsaigon333

**Comment by kangju2000** [comment]
@manudeli @bigsaigon333 

I'm back! Should I do it?

**Comment by manudeli** [comment]
> @manudeli @bigsaigon333
> 
> I'm back! Should I do it?

Cool! Could you do it please? In my opinion, after you work I want to check this Pull Request (https://github.com/toss/suspensive/pull/1123) make how much size is reduced by your work ci

Could you choose what you want? I want to depend on you for this issue

**Comment by kangju2000** [comment]
Sure! I'll pick a tool that I think is suitable and give it a try.
