### ISSUE TITLE
@suspensive/react-query-4, @suspensive/react-query-5 should be fixed version by changeset config

### ISSUE THREAD

**Issue by manudeli** [toss/suspensive#981]
https://github.com/toss/suspensive/blob/09e957c4e9a0d2e2a5789961f9242843922915a4/.changeset/config.json#L5

In my opinion, @suspensive/react-query-4, @suspensive/react-query-5 should be fixed version by changeset config. Do you agree this config?

**Comment by gwansikk** [comment]
I think it would be good to add it.

Since `@suspensive/react-query-4` and `@suspensive/react-query-5` provide the same functionality, they should be "fixed". `@suspensive/react-query` integrates these versions and should therefore have the same versioning and release cycle.
